# Render Blueprint Specification
# Docs: https://render.com/docs/infrastructure-as-code
# This file defines the infrastructure (services & databases) for Project Nexus.

databases:
  - name: nexus-postgres
    databaseName: ecommerce
    user: ecommerce
    plan: free # upgrade as needed

services:
  - type: web
    name: nexus-web
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    dockerCommand: /app/docker/entrypoint.sh runserver
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: CELERY_EAGER
        value: "false"
      - key: EMAIL_SILENT_FAIL
        value: "false"
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: ALLOWED_HOSTS
        value: "nexus-web.onrender.com,localhost,127.0.0.1"
      - key: SITE_URL
        value: https://nexus-web.onrender.com
      - key: POSTGRES_DB
        fromDatabase:
          name: nexus-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: nexus-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: nexus-postgres
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: nexus-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: nexus-postgres
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: REDIS_HOST
        value: nexus-redis
      - key: REDIS_PORT
        value: "6379"

  - type: worker
    name: nexus-worker
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    dockerCommand: /app/docker/entrypoint.sh celery-worker
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: CELERY_EAGER
        value: "false"
      - key: EMAIL_SILENT_FAIL
        value: "false"
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: POSTGRES_DB
        fromDatabase:
          name: nexus-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: nexus-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: nexus-postgres
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: nexus-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: nexus-postgres
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: REDIS_HOST
        value: nexus-redis
      - key: REDIS_PORT
        value: "6379"

  - type: worker
    name: nexus-beat
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    dockerCommand: /app/docker/entrypoint.sh celery-beat
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: CELERY_EAGER
        value: "false"
      - key: EMAIL_SILENT_FAIL
        value: "false"
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: POSTGRES_DB
        fromDatabase:
          name: nexus-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: nexus-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: nexus-postgres
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: nexus-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: nexus-postgres
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: REDIS_HOST
        value: nexus-redis
      - key: REDIS_PORT
        value: "6379"

  - type: redis
    name: nexus-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all (adjust for tighter security in production)

# Notes:
# 1. Replace console email backend with a real provider for production (SendGrid, Mailgun, etc.).
# 2. For Gunicorn: update Dockerfile or dockerCommand to invoke gunicorn instead of Django's dev server.
# 3. Ensure Celery beat schedule references valid task paths (currently some placeholders may need updating).
# 4. Remove nexus-beat service if you do not use scheduled tasks yet.
