# Generated by Django 5.2.4 on 2025-09-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_groups_user_is_staff_and_more'),
        ('users', '0002_user_email_tracking'),
    ]

    operations = [
    ]
