# Render Blueprint Specification
# Docs: https://render.com/docs/infrastructure-as-code
# This file defines the infrastructure (services & databases) for Project Nexus.

databases:
  - name: nexus-postgres
    databaseName: ecommerce
    user: ecommerce
    plan: free

services:
  - type: web
    name: nexus-web
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --verbosity 0
      python manage.py migrate --noinput
    startCommand: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 60 --access-logfile - --error-logfile -
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_SECRET_KEY
        value: REPLACE_WITH_SECURE_SECRET
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "nexus-web.onrender.com,localhost,127.0.0.1"
      - key: SITE_URL
        value: https://nexus-web.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-postgres
          property: connectionString
      - key: CELERY_EAGER
        value: "true"  # Inline task execution (no separate worker/beat services)

# Basic minimal blueprint: single web service + Postgres. Inline Celery tasks.
# To scale later:
#  - Add a Redis service and separate worker: change CELERY_EAGER to false.
#  - Add periodic tasks: create a beat worker service.
#  - Add email credentials: set EMAIL_BACKEND & related vars.
